proxy_cache_path /tmp/thumbor_cache levels=1:2 keys_zone=thumbor:10m max_size=500m inactive=7d;

server {
    listen 80;
    server_name _;

    proxy_cache thumbor;
    proxy_cache_valid 200 7d;
    proxy_cache_valid 404 1m;
    add_header X-Cache-Status $upstream_cache_status;

    location / {
        proxy_pass http://thumbor:8888;
        proxy_set_header Host $host;
        expires 7d;
        add_header Cache-Control "public";
    }
}
