<?php

return [
    'description'   => 'Permissies in Kanka kunnen worden verfijnd om precies te bepalen wat een gebruiker wel en niet kan. Je kunt zo open of beperkend zijn als je wilt, afhankelijk van je behoeften.',
    'fifth'         => 'De meeste entiteiten hebben een "privacy" checkbox-optie die alle andere permissies vervangt. Indien aangevinkt, zullen alleen leden van de beheerder rol van de campaign de entiteit zien.',
    'first'         => 'De permissies van Kanka zijn opgesplitst in verschillende concepten: rol permissies en entiteit permissies. Elke campaign wordt standaard geleverd met een Beheerder-, een Publiek- en een Speler-rol. Leden met de beheerder rol kunnen alles in een campaign zien en doen. De openbare rol wordt gebruikt als de campaign openbaar is en een gebruiker er geen deel van uitmaakt en de rol standaard geen permissies heeft. Ten slotte wordt de speler rol standaard ook zonder permissies geleverd en wordt deze gebruikt voor iedereen die deel uitmaakt van de campaign. Wanneer je een nieuw lid uitnodigt voor je campaign, bepaal je in welke rol zij zich aansluiten. Je kunt meer rollen maken en mensen verplaatsen, en je kunt ook leden in verschillende rollen hebben.',
    'fourth'        => 'Om de permissies van een gebruiker te controleren, ga je naar de ledenpagina van je campaign en klik je op de knop "Bekijken als". Deze knop is alleen beschikbaar voor campaign beheerders en kan alleen worden gebruikt voor niet-campaign beheerders. Bij het maken of bewerken van een entiteit met behulp van deze functie, wordt de informatie opgeslagen in de logboeken van de entiteit.',
    'second'        => 'Een rol kan op verschillende manieren worden ingesteld. Je kunt bijvoorbeeld leden van een rol toestaan om personages te bekijken en aan te maken, maar deze niet te bewerken of te verwijderen. Als een gebruiker een entiteit kan maken maar deze niet kan wijzigen, krijgt hij automatisch update permissies.',
    'third'         => 'Als je niet wilt dat leden van een rol alle personages kunnen zien, kun je in plaats daarvan individuele permissies voor elk personage instellen, door ze te bewerken of door de knop voor bulk permissies te gebruiken die zichtbaar is voor campaign beheerders in de lijst met personages. Dezelfde concepten zijn van toepassing op alle andere entiteitstypen.',
    'title'         => 'Permissies',
];
