<?php

return [
    'description'   => 'Les permissions dans Kanka peuvent être ajustées pour contrôler exactement ce qu\'un utilisateur peut et ne peut pas voir et faire. Cela peut être autant ouvert ou restrictif que nécessaire, basé sur les besoins du monde.',
    'fifth'         => 'La plupart des entités disposent d\'une case à cocher "confidentialité" qui écrase toutes les autres autorisations. Lorsqu\'elle est cochée, seuls les membres du rôle d\'administrateur de la campagne verront l\'entité.',
    'first'         => 'Les permissions de Kanka sont divisées en plusieurs concepts : permissions de rôle et permissions d\'entité. Par défaut, chaque campagne est fournie avec un rôle admin, un rôle public et un rôle joueur. Les membres du rôle admin peuvent tout voir et tout faire dans une campagne. Le rôle public est utilisé si la campagne est publique et qu\'un utilisateur n\'en fait pas partie. Par défaut, ce rôle n\'a aucune autorisation. Enfin, le rôle de joueur est également dépourvu d\'autorisations par défaut et est utilisé pour toute autre personne faisant partie de la campagne. Lorsque tu invites un nouveau membre à la campagne, tu définis son rôle. Tu peux également créer d\'autres rôles, déplacer des membres et avoir des membres avec plusieurs rôles.',
    'fourth'        => 'Pour vérifier les autorisations d\'un utilisateur, rends-toi sur la page des membres de la campagne et cliques sur le bouton "Usurper". Ce bouton n\'est disponible que pour les administrateurs de la campagne, et ne peut être utilisé que par des membres qui ne sont pas administrateurs de la campagne. Lorsque tu crées ou modifies une entité à l\'aide de cette fonctionnalité, les informations d\'usurpation seront enregistrées dans les logs de l\'entité.',
    'second'        => 'Un rôle peut être configuré de différentes manières. Par exemple, il peut autoriser les membres d\'un rôle à visualiser et à créer des personnages, mais pas à les modifier ou à les supprimer. Si un utilisateur peut créer une entité mais ne peut pas la modifier, il obtiendra automatiquement des autorisations de mise à jour.',
    'third'         => 'Si tu ne souhaites pas permettre aux membres d\'un rôle de voir tous les personnages, tu peux à la place définir des permissions individuellement sur chaque personnage, soit en les modifiant, soit en utilisant le bouton de permissions en bloc visible par les administrateurs de campagne sur la liste des personnages. Les mêmes concepts s\'appliquent à tous les autres types d\'entités.',
    'title'         => 'Permissions',
];
