<?php

namespace App\Http\Controllers\Crud;

use App\Datagrids\Actions\NoDatagridActions;
use App\Http\Controllers\CrudController;
use App\Models\Campaign;
use App\Models\DiceRollResult;
use Illuminate\Http\Request;

class DiceRollResultController extends CrudController
{
    /**
     * @var string
     */
    protected string $view = 'dice_roll_results';
    protected string $route = 'dice_roll_results';

    /** @var string Model */
    protected $model = \App\Models\DiceRollResult::class;

    /** @var string Filter */
    protected string $filter = DiceRollResult::class;

    protected string $forceMode = 'table';

    protected function getNavActions(): CrudController
    {
        $this->addNavAction(
            route('dice_rolls.index', $this->campaign),
            '<i class="fa-solid fa-square"></i> ' . __('dice_rolls.index.actions.dice')
        );
        return parent::getNavActions(); // TODO: Change the autogenerated stub
    }
    /**
     * Display a listing of the resource.
     */
    public function index(Request $request, Campaign $campaign)
    {
        //$this->authorize('browse', $this->model);

        $model = new $this->model();
        $this->filterService->request($request)
            ->model($model)
            ->make($this->view);
        $name = $this->view;
        $langKey = $name;
        $actions = $this->navActions;
        $filterService = $this->filterService;
        $datagridActions = new NoDatagridActions();

        $base = $model
            ->search(request()->get('search'))
            ->order($this->filterService->order())
        ;
        $unfilteredCount = $base->count();
        $base = $base->filter($this->filterService->filters());
        $filteredCount =  $base->count();
        $filter = false; //new $this->filter;
        $route = 'dice_roll_results';
        $mode = 'table';
        $forceMode = $this->forceMode;

        $models = $base->paginate();
        return view('cruds.index', compact(
            'campaign',
            'models',
            'name',
            'model',
            'actions',
            'route',
            'filter',
            'filterService',
            'filteredCount',
            'unfilteredCount',
            'langKey',
            'datagridActions',
            'mode',
            'forceMode',
        ));
    }

    /**
     * Display the specified resource.
     */
    public function show(Campaign $campaign, DiceRollResult $diceRollResult)
    {
        return redirect()->to($diceRollResult->diceRoll->getLink());
    }
}
