<?php

return [
    'description'   => 'Berechtigungen in Kanka können genau abgestimmt werden, um genau zu steuern, was ein Benutzer kann und was nicht. Sie können je nach Ihren Anforderungen so offen oder restriktiv sein, wie Sie möchten.',
    'fifth'         => 'Die meisten Objekte verfügen über eine Kontrollkästchenoption "Privat", die alle anderen Berechtigungen ersetzt. Wenn diese Option aktiviert ist, wird das Objekt nur Mitgliedern der Administratorrolle der Kampagne angezeigt.',
    'first'         => 'Kankas Berechtigungen sind in verschiedene Konzepte unterteilt: Rollenberechtigungen und Objektberechtigungen. Standardmäßig verfügt jede Kampagne über eine Administrator-, eine öffentliche und eine Spieler-Rolle. Mitglieder der Administratorrolle können alles in einer Kampagne sehen und ausführen. Die öffentliche Rolle wird verwendet, wenn die Kampagne öffentlich ist und ein Benutzer nicht Teil davon ist und die Rolle standardmäßig keine Berechtigungen hat. Schließlich enthält die Spielerrolle standardmäßig keine Berechtigungen und wird für alle Personen verwendet, die Teil der Kampagne sind. Wenn Sie ein neues Mitglied zu Ihrer Kampagne einladen, definieren Sie, welcher Rolle es beitritt. Sie können mehr Rollen erstellen, Personen verschieben und Mitglieder in mehreren Rollen haben.',
    'fourth'        => 'Um die Berechtigungen eines Benutzers zu überprüfen, rufen Sie die Mitgliederseite Ihrer Kampagne auf und klicken Sie auf die Schaltfläche "Anzeigen als". Diese Schaltfläche steht nur Kampagnenadministratoren zur Verfügung und kann nur für Nicht-Kampagnenadministratoren verwendet werden. Beim Erstellen oder Bearbeiten eines Objekts mit dieser Funktion werden die Informationen in den Protokollen der Objekte gespeichert.',
    'second'        => 'Eine Rolle kann auf verschiedene Arten eingerichtet werden. Sie können beispielsweise Mitgliedern einer Rolle erlauben, Zeichen anzuzeigen und zu erstellen, diese jedoch nicht zu bearbeiten oder zu löschen. Wenn ein Benutzer ein Objekt erstellt, aber nicht ändern kann, erhält er automatisch Aktualisierungsberechtigungen.',
    'third'         => 'Wenn Sie nicht möchten, dass Mitglieder einer Rolle alle Charaktere sehen, können Sie stattdessen die Berechtigungen für jedes Symbol einzeln festlegen, indem Sie sie entweder bearbeiten oder die Schaltfläche für Massenberechtigungen verwenden, die für Kampagnenadministratoren in der Liste der Zeichen sichtbar ist. Die gleichen Konzepte gelten für alle anderen Objekttypen.',
    'title'         => 'Berechtigungen',
];
